name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    # Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl
        tools: composer:v2
    
    # Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    # Setup .NET
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: '9.0.x'
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    # Install Node.js test dependencies
    - name: Install Node.js dependencies
      run: npm ci
      working-directory: nodejs
    
    # Pre-install dependencies for all implementations to speed up tests
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      working-directory: python
    
    - name: Install PHP dependencies
      run: composer install
      working-directory: php

    - name: Install Java dependencies
      run: mvn dependency:resolve
      working-directory: java
    
    # - name: Install .NET dependencies
    #   run: dotnet restore
    #   working-directory: dotnet
    
    - name: Install Go dependencies
      run: go mod download
      working-directory: go
    
    - name: Install Playwright browsers
      run: npm ci
      working-directory: .
    
    - name: Run E2E tests
      run: npm run test:ci
      working-directory: .
      env:
        CI: true
        PUBLIC_API_KEY: ${{ vars.PUBLIC_API_KEY }}
        SECRET_API_KEY: ${{ vars.SECRET_API_KEY }}
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          /playwright-report/
          /test-results/
        retention-days: 30
        overwrite: true
